---
version: 1.4.10-6
default-factions-plugin: FactionsPro
enable-multiworld-chat: false
groups:
  Guest:
    chat: '&e{level}&r&l{tier}&r&f{display_name}&r{prefix}&f: &f{msg}'
    nametag: '&l{tier}&r{display_name}&r{prefix}'
    worlds: []
  Admin:
    chat: '&e{level}&r&l{tier}&l&cADMIN&r&b {display_name}&r{prefix}&f: &c{msg}'
    nametag: '&l{tier}&l&cADMIN&r&b {display_name}&r{prefix}'
    worlds: []
  Executive:
    chat: '&e{level}&r&l{tier}&l&0EXECUTIVE&r&a {display_name}&r{prefix}&f: &a{msg}'
    nametag: '&l{tier}&l&0EXECUTIVE&r&a {display_name}&r{prefix}'
    worlds: []
  YouTube:
    chat: '&e{level}&r&l{tier}&l&cYOU&fTUBE&r&c {display_name}&r{prefix}&f: &c{msg}'
    nametag: '&l{tier}&l&cYOU&fTUBE&r&c {display_name}&r{prefix}'
    worlds: []
  Builder:
    chat: '&e{level}&r&l{tier}&l&eBUILDER&r {display_name}&r{prefix}&f: &e{msg}'
    nametag: '&l{tier}&l&eBUILDER&r {display_name}&r{prefix}'
    worlds: []
  Voter:
    nametag: '&l{tier}&l&3VOTER&r {display_name}&r{prefix}'
    chat: '&e{level}&r&l{tier}&l&3VOTER&r {display_name}&r{prefix}&f: &f{msg}'
  Developer:
    nametag: '&l{tier}&l&dDEVELOPER&r {display_name}&r{prefix}'
    chat: '&e{level}&r&l{tier}&l&dDEVELOPER&r {display_name}&r{prefix}&f: &d{msg}'
  Mod:
    nametag: '&l{tier}&l&9MOD&r {display_name}&r{prefix}'
    chat: '&e{level}&r&l{tier}&l&9MOD&r {display_name}&r{prefix}&f: &9{msg}'
  Designer:
    nametag: '&l{tier}&l&5DESIGNER&r {display_name}&r{prefix}'
    chat: '&e{level}&r&l{tier}&l&5DESIGNER&r {display_name}&r{prefix}&f: &d{msg}'
  Tree:
    nametag: '&l{tier}&l&2TREE&r {display_name}&r{prefix}'
    chat: '&e{level}&r&l{tier}&l&2TREE&r {display_name}&r{prefix}&f: &2{msg}'
  Dino:
    nametag: '&l{tier}&l&4DINO&r {display_name}&r{prefix}'
    chat: '&e{level}&r&l{tier}&l&4DINO&r {display_name}&r{prefix}&f: &c{msg}'
  Zero:
    nametag: '&l{tier}&l&bZ&9E&bR&9O&r {display_name}&r{prefix}'
    chat: '&e{level}&r&l{tier}&l&bZ&9E&bR&9O&r {display_name}&r{prefix}&f: &1{msg}'
  Trainee:
    chat: '&e{level}&r&l{tier}§l§bTRAINEE§r {display_name}&r{prefix}&f: §b{msg}'
    nametag: '&l{tier}§l§bTRAINEE§r {display_name}&r{prefix}'
  Beta Tester:
    chat: '&e{level}&r&l{tier}&l&3BETA&r {display_name}{prefix}&f: &3{msg}'
    nametag: '&l{tier}&l&3BETA&r {display_name}{prefix}'
  Supervisor:
    chat: '&e{level}&r&l{tier}&l&dSUPERVISOR&r {display_name}{prefix}&f: &d{msg}'
    nametag: '&l{tier}&l&dSUPERVISOR&r {display_name}{prefix}'
  Support:
    chat: '&e{level}&r&l{tier}&l&5SUPPORT&r {display_name}{prefix}&f: &5{msg}'
    nametag: '&l{tier}&l&5SUPPORT&r {display_name}{prefix}'
  Discord:
    chat: '&e{level}&r&l{tier}&l&aDISCORD&r {display_name}{prefix}&f: &a{msg}'
    nametag: '&l{tier}&l&aDISCORD&r {display_name}{prefix}'
...
